# Generated by Django 4.1.3 on 2022-11-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='swag',
            name='sets',
            field=models.ManyToManyField(to='main_app.set'),
        ),
    ]
